### ISSUE TITLE
invalid byte sequence in US-ASCII when adding SBConstants in run scrip

### ISSUE THREAD

**Issue by Broich** [paulsamuels/SBConstants#39]
Hi there,

so generating the constants from the terminal works fine. However trying to run the same command from a run script added to the build phases gives me this ruby error which seems cryptic to me as I don't know anything about the language. Do you have an idea?

```
/Library/Ruby/Gems/2.0.0/gems/sbconstants-1.1.2/lib/sbconstants/cli.rb:79:in `[]': invalid byte sequence in US-ASCII (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/sbconstants-1.1.2/lib/sbconstants/cli.rb:79:in `block (3 levels) in parse_storyboards'
	from /Library/Ruby/Gems/2.0.0/gems/sbconstants-1.1.2/lib/sbconstants/cli.rb:78:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/sbconstants-1.1.2/lib/sbconstants/cli.rb:78:in `block (2 levels) in parse_storyboards'
	from /Library/Ruby/Gems/2.0.0/gems/sbconstants-1.1.2/lib/sbconstants/cli.rb:77:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/sbconstants-1.1.2/lib/sbconstants/cli.rb:77:in `each_with_index'
	from /Library/Ruby/Gems/2.0.0/gems/sbconstants-1.1.2/lib/sbconstants/cli.rb:77:in `block in parse_storyboards'
	from /Library/Ruby/Gems/2.0.0/gems/sbconstants-1.1.2/lib/sbconstants/cli.rb:69:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/sbconstants-1.1.2/lib/sbconstants/cli.rb:69:in `each_with_index'
	from /Library/Ruby/Gems/2.0.0/gems/sbconstants-1.1.2/lib/sbconstants/cli.rb:69:in `parse_storyboards'
	from /Library/Ruby/Gems/2.0.0/gems/sbconstants-1.1.2/lib/sbconstants/cli.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sbconstants-1.1.2/lib/sbconstants/cli.rb:8:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sbconstants-1.1.2/bin/sbconstants:5:in `<top (required)>'
	from /usr/local/bin/sbconstants:23:in `load'
	from /usr/local/bin/sbconstants:23:in `<main>'
Command /bin/sh failed with exit code 1

```

**Comment by patoroco** [comment]
Hi @Broich, have you tried to add UTF8 to your config before to run script in build phase?

```
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

Also should be good to have `#encoding: utf-8` at the top of _sbconstants_, what do you thing @paulsamuels  / @orta?
